{
  parserClass="com.github.jodiew.sortlines.lang.parser.SortParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Sort"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.jodiew.sortlines.lang.psi"
  psiImplPackage="com.github.jodiew.sortlines.lang.psi.impl"

  elementTypeHolderClass="com.github.jodiew.sortlines.lang.psi.SortTypes"
  elementTypeClass="com.github.jodiew.sortlines.lang.psi.SortElementType"
  tokenTypeClass="com.github.jodiew.sortlines.lang.psi.SortTokenType"

  tokens= [
    LBRACE = '{'
    RBRACE = '}'
    COLON = ':'
    COMMA = ','
  ]
}

sortFile ::= item_*

private item_ ::= (sortOptions|CRLF)

sortOptions ::= ORDER
